### PR TITLE
Refactor: Common out head component and placed in app.js

### PR DESCRIPTION
**Pull request by saraogipraveen**
- Instead of using head component everywhere, It has been moved inside app.js
- SettingsIcon Highlight issue fix

### CODE REVIEW

**Comment by itsnitinr** [comment]
Hi @saraogipraveen, this is excellent. Thanks for contributing but I think there's an issue with `titleText` as it is being evaluated to 'Home' irrespective of the page we're on except for the home page. Can you confirm if this happens on your end as well? 

Screenshot_20210510_163133

**Comment by saraogipraveen** [comment]
> Hi @saraogipraveen, this is excellent. Thanks for contributing but I think there's an issue with `titleText` as it is being evaluated to 'Home' irrespective of the page we're on except for the home page. Can you confirm if this happens on your end as well?
> 
> Screenshot_20210510_163133

@itsnitinr  seems like the component's name gets changed into something else on deploy/build. There is an alternative by calling `getStaticProps` from each page than reading it through `pageProps` inside `_app.js`, but then it will again populate each component. Let me know if this sounds good to you else we will discard this PR. 

```
export async function getStaticProps(context) {
  return {
    props: {title: 'About'}, // will be passed to the page component as props
  }
}
```

**Comment by itsnitinr** [comment]
@saraogipraveen This is quite clever, nice! However, what do you think about defining `getStaticProps()` over importing the `<Head>` component into each page?  Either way, thank you for the changes, and let me know which approach do you think would be better. I'll merge or revert back to the custom `Head` tag on each page accordingly.

**Comment by saraogipraveen** [comment]
@itsnitinr I think later as the project grows, we might need to anyway use `getStaticProps()` in pages as per requirement. This approach looks good to me. Also, importing `<Head>` component once  > importing `<Head>` in each page

**Comment by itsnitinr** [comment]
Makes sense. Good call!

**Pull request merged**
